"""initial tables

Revision ID: 80b4a8b747ad
Revises: 9f8f22e5e27f
Create Date: 2023-04-17 10:47:02.077612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b4a8b747ad'
down_revision = '9f8f22e5e27f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.drop_column('catgory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catgory', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
