"""initial tables

Revision ID: 9f8f22e5e27f
Revises: 9384ba12ec38
Create Date: 2023-04-17 10:46:06.247345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8f22e5e27f'
down_revision = '9384ba12ec38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_item_id_orders', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_orders_item_id_items'), 'items', ['item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_item_id_items'), type_='foreignkey')
        batch_op.create_foreign_key('fk_orders_item_id_orders', 'orders', ['item_id'], ['id'])

    # ### end Alembic commands ###
